[package]
name = "sdlext"
version.workspace = true
edition.workspace = true

[dependencies]
sdl3-sys = { git = "https://codeberg.org/laladrik/sdl3-sys", rev = "f86a66e7" }
sdl3-ttf-sys = { git = "https://codeberg.org/laladrik/sdl3-ttf-sys", rev = "b2ef9dc5" }
